/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as SettingsRouteImport } from "./routes/settings"
import { Route as HelpRouteImport } from "./routes/help"
import { Route as FlowsRouteImport } from "./routes/flows"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as FlowsIndexRouteImport } from "./routes/flows/index"

const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: "/help",
  path: "/help",
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsRoute = FlowsRouteImport.update({
  id: "/flows",
  path: "/flows",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsIndexRoute = FlowsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => FlowsRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/flows": typeof FlowsRouteWithChildren
  "/help": typeof HelpRoute
  "/settings": typeof SettingsRoute
  "/flows/": typeof FlowsIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/help": typeof HelpRoute
  "/settings": typeof SettingsRoute
  "/flows": typeof FlowsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/flows": typeof FlowsRouteWithChildren
  "/help": typeof HelpRoute
  "/settings": typeof SettingsRoute
  "/flows/": typeof FlowsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/flows" | "/help" | "/settings" | "/flows/"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/help" | "/settings" | "/flows"
  id: "__root__" | "/" | "/flows" | "/help" | "/settings" | "/flows/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FlowsRoute: typeof FlowsRouteWithChildren
  HelpRoute: typeof HelpRoute
  SettingsRoute: typeof SettingsRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/settings": {
      id: "/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/help": {
      id: "/help"
      path: "/help"
      fullPath: "/help"
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/flows": {
      id: "/flows"
      path: "/flows"
      fullPath: "/flows"
      preLoaderRoute: typeof FlowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/flows/": {
      id: "/flows/"
      path: "/"
      fullPath: "/flows/"
      preLoaderRoute: typeof FlowsIndexRouteImport
      parentRoute: typeof FlowsRoute
    }
  }
}

interface FlowsRouteChildren {
  FlowsIndexRoute: typeof FlowsIndexRoute
}

const FlowsRouteChildren: FlowsRouteChildren = {
  FlowsIndexRoute: FlowsIndexRoute,
}

const FlowsRouteWithChildren = FlowsRoute._addFileChildren(FlowsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FlowsRoute: FlowsRouteWithChildren,
  HelpRoute: HelpRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
