/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as FlowsIndexRouteImport } from "./routes/flows/index"
import { Route as FlowsFlowIdIndexRouteImport } from "./routes/flows/$flowId/index"
import { Route as FlowsFlowIdEditRouteImport } from "./routes/flows/$flowId/edit"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsIndexRoute = FlowsIndexRouteImport.update({
  id: "/flows/",
  path: "/flows/",
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsFlowIdIndexRoute = FlowsFlowIdIndexRouteImport.update({
  id: "/flows/$flowId/",
  path: "/flows/$flowId/",
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsFlowIdEditRoute = FlowsFlowIdEditRouteImport.update({
  id: "/flows/$flowId/edit",
  path: "/flows/$flowId/edit",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/flows/": typeof FlowsIndexRoute
  "/flows/$flowId/edit": typeof FlowsFlowIdEditRoute
  "/flows/$flowId/": typeof FlowsFlowIdIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/flows": typeof FlowsIndexRoute
  "/flows/$flowId/edit": typeof FlowsFlowIdEditRoute
  "/flows/$flowId": typeof FlowsFlowIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/flows/": typeof FlowsIndexRoute
  "/flows/$flowId/edit": typeof FlowsFlowIdEditRoute
  "/flows/$flowId/": typeof FlowsFlowIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/flows/" | "/flows/$flowId/edit" | "/flows/$flowId/"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/flows" | "/flows/$flowId/edit" | "/flows/$flowId"
  id: "__root__" | "/" | "/flows/" | "/flows/$flowId/edit" | "/flows/$flowId/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FlowsIndexRoute: typeof FlowsIndexRoute
  FlowsFlowIdEditRoute: typeof FlowsFlowIdEditRoute
  FlowsFlowIdIndexRoute: typeof FlowsFlowIdIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/flows/": {
      id: "/flows/"
      path: "/flows"
      fullPath: "/flows/"
      preLoaderRoute: typeof FlowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/flows/$flowId/": {
      id: "/flows/$flowId/"
      path: "/flows/$flowId"
      fullPath: "/flows/$flowId/"
      preLoaderRoute: typeof FlowsFlowIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/flows/$flowId/edit": {
      id: "/flows/$flowId/edit"
      path: "/flows/$flowId/edit"
      fullPath: "/flows/$flowId/edit"
      preLoaderRoute: typeof FlowsFlowIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FlowsIndexRoute: FlowsIndexRoute,
  FlowsFlowIdEditRoute: FlowsFlowIdEditRoute,
  FlowsFlowIdIndexRoute: FlowsFlowIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
