/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as FlowsRouteImport } from "./routes/flows"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as FlowsIndexRouteImport } from "./routes/flows/index"
import { Route as FlowsFlowIdIndexRouteImport } from "./routes/flows/$flowId/index"
import { Route as FlowsFlowIdEditRouteImport } from "./routes/flows/$flowId/edit"

const FlowsRoute = FlowsRouteImport.update({
  id: "/flows",
  path: "/flows",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsIndexRoute = FlowsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => FlowsRoute,
} as any)
<<<<<<< HEAD
const FlowsNewIndexRoute = FlowsNewIndexRouteImport.update({
  id: "/new/",
  path: "/new/",
  getParentRoute: () => FlowsRoute,
} as any)
=======
>>>>>>> origin/feature/create-flow
const FlowsFlowIdIndexRoute = FlowsFlowIdIndexRouteImport.update({
  id: "/$flowId/",
  path: "/$flowId/",
  getParentRoute: () => FlowsRoute,
} as any)
const FlowsFlowIdEditRoute = FlowsFlowIdEditRouteImport.update({
  id: "/$flowId/edit",
  path: "/$flowId/edit",
  getParentRoute: () => FlowsRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/flows": typeof FlowsRouteWithChildren
  "/flows/": typeof FlowsIndexRoute
  "/flows/$flowId/edit": typeof FlowsFlowIdEditRoute
  "/flows/$flowId/": typeof FlowsFlowIdIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/flows": typeof FlowsIndexRoute
  "/flows/$flowId/edit": typeof FlowsFlowIdEditRoute
  "/flows/$flowId": typeof FlowsFlowIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/flows": typeof FlowsRouteWithChildren
  "/flows/": typeof FlowsIndexRoute
  "/flows/$flowId/edit": typeof FlowsFlowIdEditRoute
  "/flows/$flowId/": typeof FlowsFlowIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
<<<<<<< HEAD
  fullPaths:
    | "/"
    | "/flows"
    | "/flows/"
    | "/flows/$flowId/edit"
    | "/flows/$flowId/"
    | "/flows/new/"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/flows" | "/flows/$flowId/edit" | "/flows/$flowId" | "/flows/new"
  id:
    | "__root__"
    | "/"
    | "/flows"
    | "/flows/"
    | "/flows/$flowId/edit"
    | "/flows/$flowId/"
    | "/flows/new/"
=======
  fullPaths: "/" | "/flows/" | "/flows/$flowId/edit" | "/flows/$flowId/"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/flows" | "/flows/$flowId/edit" | "/flows/$flowId"
  id: "__root__" | "/" | "/flows/" | "/flows/$flowId/edit" | "/flows/$flowId/"
>>>>>>> origin/feature/create-flow
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
<<<<<<< HEAD
  FlowsRoute: typeof FlowsRouteWithChildren
=======
  FlowsIndexRoute: typeof FlowsIndexRoute
  FlowsRoute: typeof FlowsRouteWithChildren
  FlowsFlowIdEditRoute: typeof FlowsFlowIdEditRoute
  FlowsFlowIdIndexRoute: typeof FlowsFlowIdIndexRoute
>>>>>>> origin/feature/create-flow
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/flows": {
      id: "/flows"
      path: "/flows"
      fullPath: "/flows"
      preLoaderRoute: typeof FlowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/flows/": {
      id: "/flows/"
      path: "/"
      fullPath: "/flows/"
      preLoaderRoute: typeof FlowsIndexRouteImport
      parentRoute: typeof FlowsRoute
    }
<<<<<<< HEAD
    "/flows/new/": {
      id: "/flows/new/"
      path: "/new"
      fullPath: "/flows/new/"
      preLoaderRoute: typeof FlowsNewIndexRouteImport
      parentRoute: typeof FlowsRoute
    }
=======
>>>>>>> origin/feature/create-flow
    "/flows/$flowId/": {
      id: "/flows/$flowId/"
      path: "/$flowId"
      fullPath: "/flows/$flowId/"
      preLoaderRoute: typeof FlowsFlowIdIndexRouteImport
      parentRoute: typeof FlowsRoute
    }
    "/flows/$flowId/edit": {
      id: "/flows/$flowId/edit"
      path: "/$flowId/edit"
      fullPath: "/flows/$flowId/edit"
      preLoaderRoute: typeof FlowsFlowIdEditRouteImport
      parentRoute: typeof FlowsRoute
    }
  }
}

interface FlowsRouteChildren {
  FlowsIndexRoute: typeof FlowsIndexRoute
  FlowsFlowIdEditRoute: typeof FlowsFlowIdEditRoute
  FlowsFlowIdIndexRoute: typeof FlowsFlowIdIndexRoute
  FlowsNewIndexRoute: typeof FlowsNewIndexRoute
}

const FlowsRouteChildren: FlowsRouteChildren = {
  IndexRoute: IndexRoute,
  FlowsIndexRoute: FlowsIndexRoute,
  FlowsFlowIdEditRoute: FlowsFlowIdEditRoute,
  FlowsFlowIdIndexRoute: FlowsFlowIdIndexRoute,
  FlowsNewIndexRoute: FlowsNewIndexRoute,
}

const FlowsRouteWithChildren = FlowsRoute._addFileChildren(FlowsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FlowsRoute: FlowsRouteWithChildren,
  FlowsNewIndexRoute: FlowsNewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
